spring.datasource.url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Europe/Moscow
spring.datasource.username: root
spring.datasource.password: test
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: update


